### ISSUE TITLE
 SMSreceiver does not work 

### ISSUE THREAD

**Issue by LUK3D** [ming060/UnitySMSReceiver#1] opened 2020-08-29 15:37 UTC
Hello! first of all, I would like to thank you for developing this great solution. I am trying to use it in a project but the application does not react. When a new message enters it does not perform the function as expected. Please i need a help to make-it work

**Comment by ming060** [comment] 2020-08-30 09:51
Hi, @LUK3D I would like to know more about your issue.
Could you please provide more details about how to reproduce this issue?
Maybe about your environment, platform, Unity version, etc.

**Comment by LUK3D** [comment] 2020-08-30 10:05
Im using Unity 2020.1.0a18 
I downloaded the project you provided, and compiled it wi Target API level 28 and Minimum API Level 19.
NOTE: the application already has permission to read and send sms

**Comment by ming060** [comment] 2020-08-30 10:12
Diy you try that on a real device or on an Android emulator?
Is there any error message from the logcat?

**Comment by LUK3D** [comment] 2020-08-30 10:15
I tested it on a real device
It shows no error. Can I send you the project?
My project sends sms and I would like you to read it too

**Comment by ming060** [comment] 2020-08-30 10:22
Because this is a pretty old and simple demo project no longer in maintenance.
I am not able to make it running now.
It may take me some time to make it compiled and running (I will try it first).

Meanwhile, you can send me your project. I will check it later.

NOTE: I'm still using Unity 2018.4.0f1.

**Comment by LUK3D** [comment] 2020-08-30 10:27
Thank you for your time. I'll generate e Unitypackage and send it o your email.

**Comment by ming060** [comment] 2020-08-30 10:28
No problem.

**Comment by LUK3D** [comment] 2020-08-30 10:33
Sent. 🙂

**Comment by ming060** [comment] 2020-08-30 10:47
Got! I will check that later.
There are some resources maybe you can check on in the original [post](https://stackoverflow.com/questions/53652202/reading-sms-from-inbox-in-unity-android-and-ios-deployment) I created.

**Comment by ming060** [comment] 2020-10-22 03:26
While testing this on an Android device, remember to grant SMS permission from the Application settings manually.
(This should be fixed follow [App permissions best practices)](https://developer.android.com/training/permissions/usage-notes)

fix with #3

**Closed as completed** 2020-10-22 03:27 UTC
Labels: bug
